tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      mkdir -p $HOME/.config/httpie
      pip3 install httpie-astra==0.1.3
  - name: netflix_thatconference
    init: |
      gp open README.md
      nvm install node
      npm install -g npm@latest
    command: |
      git remote -v | grep datastaxdevs && echo "DO NOT USE THE DATASTAXDEVS WORKSPACE, PLEASE GO BACK TO THE INSTRUCTIONS TO SET UP YOUR OWN"
      git remote -v | grep -v datastaxdevs && echo "workshopgraphql-netflix gitpod ready - LET'S DO THIS!" && npm install
ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
  - port: 3000
    onOpen: ignore      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
